plugins {
    id 'com.android.application'
    id 'com.sameer.arora.obfuscator'
}

android {
    
    defaultConfig {
        versionCode 1
        compileSdk 37
        minSdkVersion 30
        versionName "1.0"
        targetSdkVersion 37
        buildToolsVersion "37.0.0"
        flavorDimensions "default"
        namespace "com.sameer.arora.obfuscator.asplugin"
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    Obfuscator {
    depth 2
    // 是否启用
    enabled true
    // 混淆深度
    // 需要混淆的包或者类(匹配前面一段)
    obfClass = ["com.sameer.arora", "com.abc"]
    // blackClass中的包或者类不会进行混淆(匹配前面一段)
    blackClass = ["com.sameer.arora.obfuscator.asplugin"]
}

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}


dependencies {
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
}